### ISSUE TITLE
DatetimeIndex not recognized by pvpolyfit

### ISSUE THREAD

**Issue by CameronTStark** [MichaelHopwood/PVPolyfit#1]
I'm sure you're aware but I wanted to highlight for new users that the use of a DatetimeIndex did not work for me. I had to do a `df.index = df.index.strftime('%m/%d/%Y %H:%M:%S %p')` to stringify the DatetimeIndex I had to so pvpolyfit would be able to ingest the DataFrame.

I haven't dug into the source much to be able to give a proposal on how to deal with the DatetimeIndex directly but it's definitely something desirable since working with PVLIB-python will invariable need/provide a working DatetimeIndex to produce a 'pvlib_GHI' to reference.

**Comment by MichaelHopwood** [comment]
I appreciate the feedback. I am working on publishing documentation for this package. As a message to the users: for now, please reference example/example.py for documentation and an example on this package's implementation. 

Indeed, the index must be of type string and format `'%m/%d/%Y %I:%M:%S %p'`, as you said. The PVPolyfit algorithm takes this index and changes it to datetime format when necessary. 

An [poor] example of the 'pvlib_GHI' implementation into the test/train DataFrames is located in PVPolyfit/preprocessing>add_ghi_to_df.  I do not recommend this implementation, but it may guide those who need an example.  This function is not used in the PVPolyfit algorithm; it was only meant for preprocessing steps.

As a note, the next version of PVPolyfit, which will be deployed within the week, will not require Current, GHI, or pvlib_GHI as inputs. Instead, an option will be available for those who do not collect these parameters.
